### ISSUE TITLE
Актуализировать макросы?

### ISSUE THREAD

**Issue by evbogdanov** [apofiget/smsc_api#3]
Привет и спасибо за библиотеку.

Сейчас интегрирую её в свой проект. Заметил пару неточностей в макросах:
1. https://github.com/apofiget/smsc_api/blob/master/include/smsc.hrl#L30
   Если верить документации https://smsc.ru/api/http/, код должен быть 3.
2. https://github.com/apofiget/smsc_api/blob/master/include/smsc.hrl#L20
   Либо я не туда смотрю, либо они выпилили этот код из своего API.
3. https://github.com/apofiget/smsc_api/blob/master/include/smsc.hrl#L44
   В статусе добавились новые ошибки с кодами 200, 220 и т.д.

Это только то, что сразу бросилось в глаза. Возможно, список не полный.

**Comment by apofiget** [comment]
Приветствую! Спасибо за замечания.
По наличию свободного времени постараюсь все оперативно исправить. Так же с удовольствием приму ваши pull реквесты.
